name: Update Font List
run-name: ${{ github.actor }} updated font list
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Updating font list..."
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
      - run: python generate/generate.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "[Actions] Update font list"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - run: echo "Done!"