name: Update Font List
run-name: ${{ github.actor }} updated font list
on:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
  schedule:
    - cron: '0 0 * * *'

jobs:
  Update-Font-List:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Updating font list..."
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
      - run: python generate/generate.py
      - name: Push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -m "[Auto] Update font list"
          git push
      - run: echo "Done!"